# Generated by Django 3.2.8 on 2021-10-25 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(default='empty', max_length=30)),
                ('lname', models.CharField(default='empty', max_length=30)),
                ('email', models.EmailField(default='empty', max_length=100)),
                ('password', models.CharField(default='empty', max_length=30)),
                ('role', models.CharField(default='empty', max_length=30)),
            ],
        ),
    ]
