# Generated by Django 3.2.8 on 2021-10-25 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='', max_length=30)),
                ('lastname', models.CharField(default='', max_length=30)),
                ('email', models.EmailField(default='', max_length=100)),
                ('password', models.CharField(default='', max_length=30)),
                ('role', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=40)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Application.user')),
            ],
        ),
    ]
